### ISSUE TITLE
Add all delay models

### ISSUE THREAD

**Issue by dbagchee** [dbagchee/helix-preset-viewer#3]

**Comment by maikito26** [comment]
Inform me how and I can be the monkey that inputs the data... new to HTML 5 lol.

**Comment by dbagchee** [comment]
Hey man here's what I've been doing.

- Create a preset with all the models with a specific category (or as many as you can fit in the DSP limitations)
- Export the preset
- Open the preset in a text editor and look for the block0-7 sections, there you will find the internal model name, for example:
`"@model" : "HD2_DM4SubOctFuzz",`
- I copy and paste just the model value into a list. Then sort into the same order that the model is in HX Edit
- Next format the model like the following (type will be dist, delay, etc - name will be the display name):
`"HD2_DM4SubOctFuzz": {
                "type": "dist",
                "name": "Sub Oct Fuzz"
            },`
- Then add this to the hxModels variable list in the assigned section (preferably in order)

It's tedious but pretty simple! I probably should split some of the files up as it's all in one huge file at the moment.

**Comment by dbagchee** [comment]
Here are the Delays if you want to give it a try:

[All Delay Legacy.txt](https://github.com/dbagchee/helix-preset-viewer/files/2506522/All.Delay.Legacy.txt)
[All Delays.txt](https://github.com/dbagchee/helix-preset-viewer/files/2506523/All.Delays.txt)

**Comment by pbatts** [comment]
Hello,
Great project! Thanks for open sourcing it and being open to contributions.

I’d like to pitch in and help where I can. I have experience in html, css, js etc. I have a couple other projects going right now, but they should be coming to a close soon. Then I will be able to put some time into this.

Splitting the master file up into smaller files is probably a good idea and will allow easier confirmation of completed sections.

pbatts

**Comment by maikito26** [comment]
Just tried the delays.   Let me know.  I can circle around and do more once I get some actual job done...

**Comment by dbagchee** [comment]
Thanks @maikito26 - looks great! I'm still figuring Git out a little so I mixed up the merge a little but think I got it all straightened out.

@pbatts - would love any help - I'll try to break up the files in the next few days for easier collab.

**Comment by maikito26** [comment]
If you have any other preset files pulled... let me at them!  I'm away from the HX sadly at the moment otherwise I'd grab them myself.

**Comment by dbagchee** [comment]
All I have left at the moment is reverbs - I added those to the reverb issue #9 if you have time to add them. Also I think there are the legacy delays in this ticket still :)

**Comment by dbagchee** [comment]
Just saw the legacy delays - thanks so much! Closing :)
