### ISSUE TITLE
Add all cab models

### ISSUE THREAD

**Issue by dbagchee** [dbagchee/helix-preset-viewer#7]

**Comment by dbagchee** [comment]
I’ve exported all the cabs into presets just need to do the copy/paste.

**Comment by maikito26** [comment]
Files available?  I can take this.

**Comment by dbagchee** [comment]
Here they are: 
[cabs.zip](https://github.com/dbagchee/helix-preset-viewer/files/2516092/cabs.zip)

**Comment by maikito26** [comment]
Got it

**Comment by maikito26** [comment]
#39 Pull Request Generated.

**Comment by dbagchee** [comment]
Thank you!
