### ISSUE TITLE
Add all reverb models

### ISSUE THREAD

**Issue by dbagchee** [dbagchee/helix-preset-viewer#9]

**Comment by dbagchee** [comment]
Reverb data:

[All Reverbs 2.txt](https://github.com/dbagchee/helix-preset-viewer/files/2506814/All.Reverbs.2.txt)
[All Reverbs.txt](https://github.com/dbagchee/helix-preset-viewer/files/2506815/All.Reverbs.txt)

**Comment by maikito26** [comment]
Got it

**Comment by maikito26** [comment]
Submitted Pull Request.

**Comment by dbagchee** [comment]
You rock! - merged.
